export const genres = [
    'Fantasy', 
    'Science Fiction',
    'Dystopian',
    'Adventure',
    'Romance',
    'Mystery',
    'Horror',
    'Thriller',
    'LGBTQ+',
    'Historical Fiction',
    'Young Adult',
    "Children's Fiction",
    'Memoir',
    'Biography',
    'Cooking',
    'Art & Photography',
    'Self-Help',
    'Motivational',
    'Health & Fitness',
    'History',
    'Crafts, Hobbies & Home',
    'Families & Relationships',
    'Humor & Entertainment',
    'Business & Money',
    'Law & Criminology',
    'Politics & Social Sciences',
    'Religion & Spirituality' ,
    'Education & Teaching',
    'Travel',
    'True Crime'
]